export const REGISTRATE_USER = 'REGISTRATE_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const TRACKS_LOADED = "TRACKS_LOADED";
export const PLAYLIST_CREATED = "PLAYLIST_CREATED";
export const PLAYLISTS_LOADED = "PLAYLISTS_LOADED";
export const TRACK_ADDED = "TRACK_ADDED";
